use crate::scanner::ScanResult;
use anyhow::Result;
use std::fs;
use std::path::Path;

const DEX_README: &str = r#"# .dex/ — Codebase Context Directory

This directory was generated by `dex init` (https://github.com/dexs-oss/dex).

It contains a structured, machine-readable description of this project's
architecture, conventions, and critical paths. Both humans and AI agents
can use these files to quickly understand the codebase.

## Files

- `context.toml` — Project metadata: languages, frameworks, build systems, structure
- `paths.toml` — Entry points, critical paths, public API surface

## Usage

Commit this directory to version control. Run `dex sync` to keep it updated.

## Learn more

https://github.com/dexs-oss/dex
"#;

/// Write the .dex/ directory with all generated files.
pub fn write_dex_dir(root: &Path, result: &ScanResult) -> Result<()> {
    let dex_dir = root.join(".dex");
    fs::create_dir_all(&dex_dir)?;

    fs::write(dex_dir.join("README"), DEX_README)?;

    let context_toml = toml::to_string_pretty(&result.context)?;
    fs::write(dex_dir.join("context.toml"), context_toml)?;

    let paths_toml = toml::to_string_pretty(&result.paths)?;
    fs::write(dex_dir.join("paths.toml"), paths_toml)?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::context::*;
    use crate::models::paths::*;

    #[test]
    fn test_write_dex_dir() {
        let dir = tempfile::tempdir().unwrap();
        let result = ScanResult {
            context: Context {
                project: Project {
                    name: "test".into(),
                    project_type: "cli".into(),
                    languages: vec!["rust".into()],
                    frameworks: vec![],
                    build_systems: vec!["cargo".into()],
                    description: None,
                    repository: None,
                },
                structure: Structure {
                    style: "modular".into(),
                    source_roots: vec!["src/".into()],
                    test_roots: vec![],
                    config_root: None,
                    workspaces: None,
                },
                status: Status {
                    schema_version: 1,
                    dex_version: "0.1.0".into(),
                    last_sync: "2026-03-14T00:00:00Z".into(),
                },
            },
            paths: Paths {
                entry_points: vec![EntryPoint {
                    name: "main".into(),
                    file: "src/main.rs".into(),
                    description: Some("Rust binary entry point".into()),
                }],
                critical_paths: vec![],
                public_api: vec![],
            },
        };

        write_dex_dir(dir.path(), &result).unwrap();

        assert!(dir.path().join(".dex/README").exists());
        assert!(dir.path().join(".dex/context.toml").exists());
        assert!(dir.path().join(".dex/paths.toml").exists());

        let ctx_content = fs::read_to_string(dir.path().join(".dex/context.toml")).unwrap();
        assert!(ctx_content.contains("name = \"test\""));
        assert!(ctx_content.contains("schema_version = 1"));
    }
}
